---
title: | 
  <div style="margin-top:45px; font-size:30px !important;">Meet Us!</div>
output:
  html_document:
    toc: true
    toc_float: true
---

Thank you so much for visiting our website! We are a team of first-year MS students at Columbia University’s Mailman School of Public Health. With five diverse undergraduate backgrounds among us, we share a common goal: to make this project a resounding success!  

### Yuhao Chang

Hi! My name is Yuhao Chang, and I am currently a first-year Master's student in Biostatistics at the Mailman School of Public Health. I completed my undergraduate studies in marine science, and transitioning to biostatistics has been a significant shift for me, one that I am thoroughly enjoying. In my free time, I enjoy city walking and exploring bakery shops.

Please contact me if you have any questions! Here is my email address: yc4585@cumc.columbia.edu 

### Yingyu Cui

Hi every one! I am a 1st year MS Epidemiology student at Mailman School of Public Health. I majored in Clinical Medicine in my undergraduate degree. In my free time, I prefer to watch movies and listen to music. I am also a big fan of traveling.

Here is my email address: yc4584@cumc.columbia.edu
I am looking forward to working with you all!

### Shangzi Gao  

[Learn more about Shangzi](https://sg4489.github.io/p8105_hw4_sg4489.github.io/)

### Jiawa Zhang

### Alice Zhou

Hi! I am Alice Zhou. I am a first-year MS student in Biostatistics at Columbia Mailman School of Public Health. Before attending Columbia, I studied Psychology and Philosophy at NYU. My research interests include the cognitive neuroscience of decision-making, particularly visual perception and movement planning. In my free time, I like going to classical music concerts, dancing and watching ballet.

Here is my email address: az2852@cumc.columbia.edu.