---
title: "Analyzing Trends and Patterns in Mortality Data"
subtitle: "A Study on Causes of Death Across U.S. States from 2020 to 2023"
output: github_document
---

### Group members (names and UNIs)

This is the final project of p8105 by Yuhao Chang(yc4585), Yingyu Cui(yc4584), Shangzi Gao(sg4489), Jiawa Zhang(jz3900), and Alice Zhou(az2852), sorted alphabetically by last name.  

### Tentative project title  

Analyzing Trends and Patterns in Mortality Data: A Study on Causes of Death Across U.S. States from 2020 to 2023  

### Anticipated data sources  

The primary data source will be the National Center for Health Statistics: Weekly Provisional Counts of Deaths by State and Select Causes, 2020-2023. Available from https://data.cdc.gov/d/muzy-jte6.  

### Motivation and planned analyses / visualizations / coding challenges for this project

The COVID-19 pandemic has highlighted the need for a deeper understanding of mortality trends to improve public health planning and response. By analyzing the “Weekly Provisional Counts of Deaths by State and Select Causes” dataset for 2020-2023, we aim to identify trends in various causes of death, including the direct and indirect impacts of COVID-19.  

Our goals are as follows: First, to uncover seasonal and geographic variations in mortality, aiding in effective resource allocation and public health interventions. Second, to explore healthcare disparities across states and diseases, highlighting unequal access to care. Third, to analyze COVID-19-specific data to understand how the pandemic affected mortality from both COVID-19 and non-COVID-19 causes.  

The analysis will generate insights into changing mortality patterns and inform evidence-based public health strategies.  

### Intended final products  

The final product will be an interactive website featuring data summaries, comparisons, and visualizations, making it easier for policymakers and the public to grasp the implications of these trends and prepare for future health challenge.  

We will create a webpage including an interactive dashboard that allows users to explore the data by year, state, and cause of death, a detailed report with data analysis and visualizations highlighting significant findings in mortality trends. And we will present our outcomes in a video.  

### Planned timeline  

*Week 1*: Process data and conduct initial exploratory data analysis.  
*Week 2*: Conduct time series and geospatial analysis.  
*Week 3*: Develop visualizations and finalize products.  
*Week 4*: Build the webpage and compile final reports.  
*Week 5* : Make introductory video, prepare presentation and finalize all deliverables.  

